GET http://localhost:8080/api/v1/user/list
Authorization: Basic admin admin

###

GET http://localhost:8080/api/v1/user/3/id

###

POST http://localhost:8080/api/v1/user/
Content-Type: application/json

{
  "id": 2,
  "login": "user2",
  "password": "user2"
}


###

PUT http://localhost:8080/api/v1/user/
Content-Type: application/json

{
  "id": 1,
  "login": "admin",
  "password": "admin"
}

###

DELETE http://localhost:8080/api/v1/user/3/id

###

GET http://localhost:8080/api/v1/product/list

###

GET http://localhost:8080/api/v1/product/3/id

###

POST http://localhost:8080/api/v1/product/
Content-Type: application/json

{
  "id": 1,
  "title": "MacBook Air",
  "description": "Small and powerful",
  "price": 280000
}

###

DELETE http://localhost:8080/api/v1/product/2/id